config/routes.rb
Rails.application.routes.draw do
  get 'tools/index'
  devise_for :users, controllers: { 
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
    }

  root 'piano#index'
  get '/questions/sound', to: 'questions#sound'#音感
  get '/questions/score', to: 'questions#score'#楽譜
  get '/questions/code', to: 'questions#code'#コード
  get '/contacts', to: 'contacts#new'#問い合わせ
  get '/tools/metronome', to: 'tools#metronome'#メトロノーム
  get '/tools/watch', to: 'tools#watch'#記録
  get '/tools/code', to: 'tools#code'#記録
  get '/tools/key', to: 'tools#key'#記録
  get '/tools/check', to: 'tools#check'#記録
  get '/tools/checkcode', to: 'tools#checkcode'#記録
  # get '/tools/search', to: 'tools#search', defaults: { format: :json }
  # resources :search, only: :index, defaults: { format: :json }
  resources :theories

  resources :search, only: :index, defaults: { format: :json }
  resources :tttt,          only: [:index, :create, :update, :destroy]
  
  resources :tools,          only: [:create, :update, :destroy]
  resources :contacts,          only: [:create]
  
  namespace :admin do
    resources :contacts, only: [:index]
  end
  namespace :admin do
    resources :users, only: [:index]
  end
  resources :users, only: [:show]
  get '/mypage' => 'users#mypage'
  resources :profiles,          only: [:create, :update, :destroy]
  get 'card/edit'# app/views/card/edit.html.erb画面にアクセス
  post 'card/create'# cardコントローラーのcreateアクション実行

  get 'card/destroy'# app/views/card/destroy.html.erb画面にアクセス
  put 'card/cancel_subscription'# cardコントローラーのcancel_subscriptionアクション実行

  get 'card/restart'# app/views/card/restart.html.erb画面にアクセス
  put 'card/restart_subscription'# cardコントローラーのrestart_subscriptionアクション実行

  get 'card/fin_subscription'# app/views/card/fin_subscription.html.erb画面にアクセス
end

app/controllers/tttt_controller.rb
class TtttController < ApplicationController
    def index
        @tool = Tool.new
        @tools = Tool.where(user_id: current_user.id)
     end
  
      private
      def note_params
        params.require(:tool).permit(:year,:month,:day,:time,:memo).merge(user_id: current_user.id)
      end
end

app/helpers/tttt_helper.rb
module TtttHelper
end

app/views/tttt/index.html.erb
<div class="notes">
  <%  @tools.each do |note| %>
  <div class="note" id="note<%= note.id %>">
    <span class="note_name">
      <%= note.id %>
    </span>
    <span class="note_name">
      投稿者：<%= note.user.name %>
    </span><span class="note_name">
      user_id<%= note.user.id %>
    </span>
    <span class="note_name">
      <%= note.year %>/
    </span>
    <span class="note_name">
      <%= note.month %>/
    </span>
    <span class="note_name">
      <%= note.day %>/
    </span>
    <span class="note_name">
    @@時間::
      <%= note.time %>/
    </span>
    <p class="note_name">
      <%= note.memo %>
    </p>
    <div class="notes">
        <div class="note" id="note<%= note.id %>">
          <span class="note_name">
          </span>
            <%= link_to "削除", tool_path(note.id) ,class: "note_delete", method: :delete %>
        </div>

  </div>
  <% end %>
</div>
<h4>メモアプリ（サンプル）</h4>
<div class="form">
  <% if user_signed_in? %>

  <textarea id="watch_year" name="tool[year]"></textarea>
  <textarea id="watch_month" name="tool[month]"></textarea>
  <textarea id="watch_day" name="tool[day]"></textarea>
  <textarea id="watch_time" name="tool[time]"></textarea>
  <textarea id="watch_memo" name="tool[memo]"></textarea>
  <input type="submit" name="commit" value="メモを登録" class="note_form-btn" id="tool_from" data-disable-with="メモを登録">
  <% end %>
</div>
<h1>検索</h1>
<div class="contents">
  <%= text_field_tag :id,'', class: 'js-text_field', placeholder: 'id' %>
  <%= text_field_tag :year,'', class: 'js-text_year', placeholder: '年' %>
  <%= text_field_tag :month,'', class: 'js-text_month', placeholder: '月' %>
</div>
<button id="search">kensaku</button>
<button id="update">更新</button>


<%= javascript_pack_tag 'tttt/index' %>