config/routes.rb
Rails.application.routes.draw do
  get 'tools/index'
  devise_for :users, controllers: { 
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
    }

  root 'piano#index'
  get '/questions/sound', to: 'questions#sound'#音感
  get '/questions/score', to: 'questions#score'#楽譜
  get '/questions/code', to: 'questions#code'#コード
  get '/contacts', to: 'contacts#new'#問い合わせ
  get '/tools/metronome', to: 'tools#metronome'#メトロノーム
  get '/tools/watch', to: 'tools#watch'#記録
  get '/tools/code', to: 'tools#code'#記録
  get '/tools/key', to: 'tools#key'#記録
  get '/tools/check', to: 'tools#check'#記録
  get '/tools/checkcode', to: 'tools#checkcode'#記録
  # get '/tools/search', to: 'tools#search', defaults: { format: :json }
  # resources :search, only: :index, defaults: { format: :json }
  resources :theories

  resources :search, only: :index, defaults: { format: :json }
  resources :tttt,          only: [:index, :create, :update, :destroy]
  
  resources :tools,          only: [:create, :update, :destroy]
  resources :contacts,          only: [:create]
  
  namespace :admin do
    resources :contacts, only: [:index]
  end
  namespace :admin do
    resources :users, only: [:index]
  end
  resources :users, only: [:show]
  get '/mypage' => 'users#mypage'
  resources :profiles,          only: [:create, :update, :destroy]
  get 'card/edit'# app/views/card/edit.html.erb画面にアクセス
  post 'card/create'# cardコントローラーのcreateアクション実行

  get 'card/destroy'# app/views/card/destroy.html.erb画面にアクセス
  put 'card/cancel_subscription'# cardコントローラーのcancel_subscriptionアクション実行

  get 'card/restart'# app/views/card/restart.html.erb画面にアクセス
  put 'card/restart_subscription'# cardコントローラーのrestart_subscriptionアクション実行

  get 'card/fin_subscription'# app/views/card/fin_subscription.html.erb画面にアクセス
end

app/models/theory.rb
class Theory < ApplicationRecord
    validates :text, presence: true
end

app/controllers/theories_controller.rb
class TheoriesController < ApplicationController
  before_action :if_not_admin, except: [:index, :show]
  def index
    @page = "theory"
    @theory = Theory.all.page(params[:page]).per(12)
  end
  def new
    @theory = Theory.new
  end
  def show
    @theory = Theory.find(params[:id])
  end
  def edit
    @theory = Theory.find(params[:id])
  end

  def update
      @theory = Theory.find(params[:id])
      if @theory.update_attributes(theory_params)
        redirect_to theories_path
        # 更新に成功した場合を扱う。
      else
        render 'edit'
      end
    end
  def destroy
    @theory =  Theory.find(params[:id])
    if @theory.destroy
      redirect_to theories_path
    end
  end


  def create
      @theory = Theory.new(theory_params)
      if  @theory.save
        redirect_to theories_path
      else
        @error = 1
        render :new
      end
  end

  def theory_params
      params.require(:theory).permit(:text,:title,:category)
  end
end

app/helpers/theorys_helper.rb
module TheorysHelper
end

app/views/share/theory/_base.html.erb
<div class="theory">
    <%= render 'share/header' %>
    <div class="container">
        <div class="flex top_content">
            <%= yield(:theory) %>
          

   

            <section class="ad_section">
                <section>
                    <%# セレクト %>
                             <%= render 'share/sidebar/sidebar' %>

                </section>
            </section>
        </div>
    </div>
</div>
<%= javascript_pack_tag 'theory/index' %>

app/views/share/theory/_index.html.erb
<div class="theory_container">
    <div class="top_theme">Theory</div>
    <div class="flex_sb theory_wrap">
        <% for t in @theory %>
        <div class="theory_contnt hoge">
            <%= link_to "i", theory_path(t.id) %>
            <div class="aic">
                <%= image_tag("/images/theory/theory.png", class:"theory_image") %>
                <span class="theory_title"><%= t.title%></span>
                <!-- <%= link_to "削除", theory_path(t.id) , method: :delete, data: { confirm: '削除しますか？' } %> -->
            </div>
            <div class="flex update_time"><img class="up_icon" src="/up_icon.png">
                <div class="theory_box">
                    <%= t.updated_at.strftime('%Y/%m/%d') %>
                </div>
            </div>
        </div>
        <% end %>
        <% if @page != "index" %>
        <div class="page_nate w100">
            <%= paginate @theory %>
        </div>
        <%else%> 
    
        <div class="readmore w100"><%= link_to 'READ MORE', theories_path %><div class="flex arror_block">
            <div class="Arrow-Right"><%= link_to '', theories_path %></div>
            <div class="Arrow-Right"><%= link_to '', theories_path %></div>
<!-- 
            <div class="Arrow-Right"><%= link_to '', theories_path %></div>
            <div class="Arrow-Right"><%= link_to '>>', theories_path %></div> -->
        </div></div>

        <% end %>
    </div>
</div>

app/views/share/theory/_insert_content.html.erb
<div class="row jfc js_theory_block">
    <div>
        <textarea id="insert_save_text" cols="30" rows="10"></textarea>
    </div>
    <div class="">
        <%= form_for(@theory) do |f| %>
        <p>タイトル</p>
        <%= f.text_field :title %>
        <p>カテゴリー</p>
        <%= f.text_field :category %>
        <p>内容</p>
        <%= f.text_area :text %>
        <%= f.submit "create", class: "action_btn" %>
        <% end %>
    </div>
    <div class="js_input_block flex">
        <div class="">
            <p>h1タイトル</p>
            <textarea id="h1_input" cols="50" rows="4"></textarea>
            <p>tip_titles目次</p>
            <textarea id="tip_titles" cols="50" rows="4"></textarea>
            <p>tip_contents中身</p>
            <div class="insert_tip_contens">
                <textarea class="tip_contents" cols="50" rows="4"></textarea>
            </div>
            <button class="theory_input_btn" id="add_content">コンテント追加</button>
        </div>
        <div class="">

            <p>is_text文章</p>
            <div class="insert_is_text">
                <textarea class="is_text" cols="50" rows="4"></textarea>
            </div>
            <button class="theory_input_btn" id="add_text">テキスト追加</button>
            <p>summaryまとめ</p>
            <textarea id="summary" cols="50" rows="4"></textarea>
        </div>
    </div>
    <button id="preview">プレビュー</button>
</div>

<button id="theory_edit_btn">編集</button>
<div class="theory">
    <%= render 'share/header' %>
    <div class="container">
        <div class="flex top_content">
            <div class="theory_show_container">
                <!-- w94から下 -->
                <div class="w94">
                    <div class="tip_list">
                        <ul id="insert_tip">
                        </ul>
                    </div>
                    <div id="insert_content">
                    </div>

                    <h2 class="ch cl">まとめ</h2>
                    <div class="summary">
                        <ul id="insert_summary">
                        </ul>
                    </div>
                </div> <!-- ここまでから上を消す -->
                <!-- ここまで -->
            </div>
            <section class="ad_section">
                <section>
                    <%# セレクト %> 
          <%= render 'share/sidebar/sidebar' %>

                </section>
            </section>
        </div>
    </div>
</div>